--- 
abstract: Replicate an SVN repository
author: Adam Jacob <adam@hjksolutions.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: SVN-Replicate
no_index: 
  directory: 
    - inc
    - t
requires: 
  Pod::Usage: 0
version: 0.01
